project_id = "qbyezofoygfeqxvtfhby"

[auth.password_requirements]
enable_password_strength = true
min_length = 8
enable_hibp = true

[functions.create-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.mp-exchange-token]
verify_jwt = false

[functions.refresh-mp-token]
verify_jwt = false
